---
title: "Forecasting Volatility"
author: "Hannah de Nobrega"
date: "2023-10-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)
pacman::p_load(tidyverse, devtools, FactoMineR, factoextra, broom, rmsfuns, readr, stochvol, tsBSS, psych, rugarch, rmgarch, forecast, tbl2xts, lubridate, PerformanceAnalytics, ggthemes, MTS, robustbase, cowplot, knitr)


# load code scripts for functions
list.files('code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))


data <- read_csv("data/quantathon_hannah.csv")
pcaseries <- lapply(data[,-1],as.double)
pcaseries <- data

```

```{r dendrogram}
# pcaseries <- all data 
# pcaseries must be in wide format
pcaseries <-  pcaseries[, colSums(is.na(pcaseries)) < nrow(pcaseries)]   # remove Columns with only NA
pcaseries[is.na(pcaseries)] <- 0

demean = scale(pcaseries[,-1], center = TRUE, scale = TRUE)
sigma <- cov(demean)

devtools::source_gist("https://gist.github.com/Nicktz/bd2614f8f8a551881a1dc3c11a1e7268")
cluster_aux()
pacman::p_load(cluster, fmxdat)

corr <- cov2cor(sigma)
distmat <- ((1 - corr)/2)^0.5
distmat <- ((1 - corr)/2)^0.5
cluster <- cluster::agnes(dist(distmat), method = "ward")
D <- dist(PCA_AllData)
hc <- hclust(D, method = 'average')
hcdata <- dendro_data_k(cluster, 4)
p <- plot_ggdendro(hcdata, direction = "lr", expand.y = 0.2)
cols <- c("#a9a9a9", "#1f77b4", "#ff7f0e", "#2ca02c", "#AD3636")
p <- plot_ggdendro(hcdata, direction = "tb", scale.color = cols,
    label.size = 2.5, branch.size = 0.5, expand.y = 0.2)
p <- p + theme_void() + expand_limits(x = c(-1, 32))
# p + labs(title = "Dendogram of EM Currencies", caption = "Dendogram created using Ward distances and AGNES clustering")
p
```


```{r pca, echo=FALSE}

# save the supplementary variables' positions:
SuppPos <- grep("Supp1|supp2", colnames(PCA_AllData)) #|Gold|Oil|Bcom_

# PCA_AllData_nodate <- PCA_AllData[,-1]
df_PCA <- PCA(PCA_AllData, quanti.sup = SuppPos, graph = FALSE,  scale.unit = TRUE)

# detect outliers
outlier(PCA_AllData, plot = TRUE, na.rm = TRUE)

# scree plot
fviz_screeplot(df_PCA, ncp = 10) 

fviz_pca_var(df_PCA, col.var = c("cos2", "contrib", "coord", 
    "x", "y")[1]) + scale_color_gradient2(low = "white", mid = "blue", 
    high = "red", midpoint = 0.5) + theme_minimal()

# Contributions of variables to PC1
fviz_contrib(df_PCA, choice = "var", axes = 1, top = 10)

# Contributions of variables to PC2
fviz_contrib(df_PCA, choice = "var", axes = 2, top = 10)
```


```{r garch, echo=FALSE}

demean = scale(PCA_AllData, center = TRUE, scale = TRUE)

demean <-  demean[, colSums(is.na(demean)) < nrow(demean)] # remove col with only na

date <- PCA_AllData_with_date[,1]

demean <- cbind(date, demean) %>% gather(Tickers, Return, -date) %>% tibble::as_tibble()  %>% dplyr::filter(date <= "2008-01-01")

xts_rtn <- demean %>% tbl2xts::tbl_xts(., cols_to_xts = "Return", spread_by = "Tickers")

plotGOGARCH(xts_rtn)

```



```{r high_vs_low_vol_periods}

Idxs <- PCA_AllData_with_date %>% 
    gather(Tickers, Return, -date) %>% 
    filter(!is.na(Return)) %>%
    filter(Tickers !="SouthAfrica") %>% 
    mutate(YearMonth = format(date, "%Y%B"))


# Consider only indexes with data from before 20080101, and use this as a common start date too...:
# Can you argue why? - beacuase of GFC
Idx_Cons <- Idxs %>% 
    group_by(Tickers) %>% 
    filter(date == first(date)) %>% 
    ungroup() %>% 
    filter(date < ymd(20080101)) %>%  
    pull(Tickers) %>% unique # make a list of all the tickers that exist pre-GFC

Idxs <- Idxs %>% 
    filter(Tickers %in% Idx_Cons) %>%  # only keep tickers that existed pre-GFC
    filter(date > ymd(20080101))

# Winzorising: mitigate the effect of extreme values
Idxs <- Idxs %>% 
    group_by(Tickers) %>% 
    mutate(Top = quantile(Return, 0.99), Bot = quantile(Return, 0.01)) %>% 
    mutate(Return = ifelse(Return > Top, Top, ifelse(Return < Bot, Bot, Return))) %>% 
    ungroup()

# do periods of high and low volatility in the rand affect the performance of South African bank return prices

zar <- PCA_AllData_with_date %>% 
    gather(Tickers, Return, -date) %>% 
    filter(date > ymd(20080101)) %>% 
    filter(Tickers == "SouthAfrica")


ZARSD <- zar %>% 
    mutate(YearMonth = format(date, "%Y%B")) %>% 
    group_by(YearMonth) %>% summarise(SD = sd(Return)*sqrt(52)) %>% 
  # Top Decile Quantile overall (highly volatile month for ZAR:
    mutate(TopQtile = quantile(SD, 0.8),
           BotQtile = quantile(SD, 0.2))


Hi_Vol <- ZARSD %>% filter(SD > TopQtile) %>% pull(YearMonth)

Low_Vol <- ZARSD %>% filter(SD < BotQtile) %>% pull(YearMonth)

perf_hi <- Perf_comparisons(Idxs, YMs = Hi_Vol, Alias = "High_Vol")

perf_lo <- Perf_comparisons(Idxs, YMs = Low_Vol, Alias = "Low_Vol")
```


```{r high, fig.cap = "Standard deviation and correlation ratio in periods of high Rand volatility \\label{high}"}
kable(perf_hi, caption = "Standard deviation and correlation ratio in periods of high Rand volatility \\label{high}")
```


```{r low, fig.cap = "Standard deviation and correlation ratio in periods of low Rand volatility  \\label{low}"}
kable(perf_lo, caption = "Standard deviation and correlation ratio in periods of low Rand volatility \\label{low}")
```



